@To_Do_API_HostAddress = https://localhost:7210

GET {{To_Do_API_HostAddress}}/GetToDoItems

###

@id=1
GET {{To_Do_API_HostAddress}}/GetToDoItemsById/{{id}}

###

POST {{To_Do_API_HostAddress}}/CreateAnItem
Content-Type: application/json

{
  "name": "walk dog",
   "isComplete": false
}

###


PUT {{To_Do_API_HostAddress}}/{id}
Content-Type: application/json

{
  //TodoItem
}

###
