@To_Do_API_HostAddress = https://localhost:7210

GET {{To_Do_API_HostAddress}}/GetToDoItems

###

@id=1
GET {{To_Do_API_HostAddress}}/{id}

###

POST {{To_Do_API_HostAddress}}/CreateAnItem
Content-Type: application/json

{
  "name": "walk dog",
   "isComplete": false
}

###

@id=3
PUT {{To_Do_API_HostAddress}}/{id}
Content-Type: application/json

{
  "Name" : "walking dog",
  "isComplete" : true
}

###

@id=3
DELETE {{To_Do_API_HostAddress}}/{id}

###

